name: tfsec

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["management-account", "organisation-security"]
    steps:
      - uses: actions/checkout@v3
      - uses: tfsec/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
          working_directory: ${{ matrix.directory }}
          tfsec_version: latest
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
