name: tfsec

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["management-account", "organisation-security"]
    steps:
      - uses: actions/checkout@main
      - uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
          working_directory: ${{ matrix.directory }}
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
